# Command used to create database in MySql:
# create database icn_development
# character set utf8 collate utf8_general_ci

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost
  port: 3306
  username: fhenrique
  password: ''

development:
  <<: *default
  database: airbnb_rails_development

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] %>

test:
  <<: *default
  database: airbnb_rails_test